# Site settings
title: Luan Moises dos Santos Valadares
description: Estudante de Licenciatura em Matemática
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Luan Moises dos Santos Valadares
user_description: Derrotado na vida.
user_title: Estudante de Licenciatura em Matemática
email: luan.moises@ufv.br
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
